sudo: false
language: python
python:
  - "3.4"
  - "3.5"
services:
  - rabbitmq # will start rabbitmq-server
cache:
  - apt
  - pip
addons:
  postgresql: "9.4"
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - postgresql-plpython-9.4
before_script:
  - psql -c 'create database taiga;' -U postgres
install:
  - pip install -r requirements-devel.txt
script:
  - coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' -m py.test -v --tb=native
after_success:
  - coveralls
