language: python
python:
  - "3.4"
services:
  - rabbitmq # will start rabbitmq-server
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database taiga;' -U postgres
install:
  - sudo apt-get install postgresql-plpython-9.3
  - pip install -r requirements-devel.txt --use-mirrors
script:
    - coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' -m py.test -v --tb=native
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andrei.antoukh@gmail.com
      - bameda@dbarragan.com
      - anler86@gmail.com
    on_success: change
    on_failure: change
after_success:
  - coveralls
